port: 3000
maxSizeMass: 50
maxMoveSpeed: 10
massDecreaseRatio: 1000
foodMass: 1
newFoodPerPlayer: 30
respawnFoodPerPlayer: 1
foodRandomWidth: 500
foodRandomHeight: 500
maxFoodCount: 50
noPlayer: 0
defaultPlayerSize: 10
eatableMassDistance: 5
